#Aakrit Prasad - Semaphore lab makefile
all:producer consumer

producer:producer.c
	gcc -o producer -Wall -g producer.c
consumer:consumer.c
	gcc -o consumer -Wall -g consumer.c
clean:
	rm -rf consumer producer
